name: Run Python tests
on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Copy env file
        run: cp .env.example .env

      - name: Fix permissions
        run: sudo chown -R 1001:1001 .

      - name: Build the stack
        run: docker-compose up --build -d

      - name: Run some tests in the container
        run: docker exec --user mathesar mathesar_service_1 sh -c "id && pwd && ls -la && ls -la /home/mathesar/code/ && ls -ld /home/mathesar/code/"

      - name: Run tests with pytest
        run: docker exec --user mathesar mathesar_service_1 pytest
